[package]
name = "imgui-sys"
version = "0.1.0-pre"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>"]
description = "Raw ocornut/imgui bindings for Rust"
homepage = "https://github.com/gekkio/imgui-rs"
repository = "https://github.com/gekkio/imgui-rs"
license = "MIT"
build = "build.rs"

[features]
default = ["glium"]

[dependencies]
bitflags = "0.7"
libc = "0.2"

[dependencies.glium]
version = "0.16"
default-features = false
optional = true

[build-dependencies]
gcc = "0.3"
